/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Dell
 */
public class calc extends javax.swing.JFrame {

    double num1, num2;
    char op;

    /**
     * Creates new form NewJFrame
     */
    public calc() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        screan = new javax.swing.JTextField();
        show = new javax.swing.JLabel();
        cl_8 = new javax.swing.JButton();
        cl_9 = new javax.swing.JButton();
        cl_7 = new javax.swing.JButton();
        chang = new javax.swing.JButton();
        cl_sub = new javax.swing.JButton();
        cl_6 = new javax.swing.JButton();
        cl_4 = new javax.swing.JButton();
        cl_5 = new javax.swing.JButton();
        cl_add = new javax.swing.JButton();
        cl_1 = new javax.swing.JButton();
        cl_3 = new javax.swing.JButton();
        cl_2 = new javax.swing.JButton();
        cl_0 = new javax.swing.JButton();
        cl_equal = new javax.swing.JButton();
        cl_boint = new javax.swing.JButton();
        cl_clear = new javax.swing.JButton();
        cl_multi = new javax.swing.JButton();
        cl_divi = new javax.swing.JButton();
        cl_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        screan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        show.setBackground(new java.awt.Color(204, 204, 204));
        show.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        show.setToolTipText("");

        cl_8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_8.setText("8");
        cl_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberAcion(evt);
            }
        });

        cl_9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_9.setText("9");
        cl_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberAcion(evt);
            }
        });

        cl_7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_7.setText("7");
        cl_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberAcion(evt);
            }
        });

        chang.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        chang.setText("±");
        chang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changActionPerformed(evt);
            }
        });

        cl_sub.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_sub.setText("-");
        cl_sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorsAcion(evt);
            }
        });

        cl_6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_6.setText("6");
        cl_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberAcion(evt);
            }
        });

        cl_4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_4.setText("4");
        cl_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberAcion(evt);
            }
        });

        cl_5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_5.setText("5");
        cl_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberAcion(evt);
            }
        });

        cl_add.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_add.setText("+");
        cl_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorsAcion(evt);
            }
        });

        cl_1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_1.setText("1");
        cl_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberAcion(evt);
            }
        });

        cl_3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_3.setText("3");
        cl_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberAcion(evt);
            }
        });

        cl_2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_2.setText("2");
        cl_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberAcion(evt);
            }
        });

        cl_0.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_0.setText("0");
        cl_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberAcion(evt);
            }
        });

        cl_equal.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_equal.setText("=");
        cl_equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl_equalActionPerformed(evt);
            }
        });

        cl_boint.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_boint.setText(".");
        cl_boint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl_bointActionPerformed(evt);
            }
        });

        cl_clear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_clear.setText("c");
        cl_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl_clearActionPerformed(evt);
            }
        });

        cl_multi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_multi.setText("×");
        cl_multi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorsAcion(evt);
            }
        });

        cl_divi.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_divi.setText("÷");
        cl_divi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorsAcion(evt);
            }
        });

        cl_back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cl_back.setText("←");
        cl_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cl_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(screan, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cl_1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                            .addComponent(cl_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cl_2, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                            .addComponent(cl_boint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cl_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cl_3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cl_add, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(chang, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(show, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cl_7, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(cl_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cl_8, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                            .addComponent(cl_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cl_back, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cl_9, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cl_5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cl_6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cl_sub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cl_multi, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(cl_divi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(show, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(screan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chang, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_back, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_divi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_multi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_sub, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_add, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cl_0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_boint, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cl_equal, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberAcion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberAcion
        // TODO add your handling code here:
        switch (evt.getActionCommand()) {
            case "0":
                if (screan.getText().length() > 0) {

                    screan.setText(screan.getText() + "0");
                }
                break;
            case "1":
                screan.setText(screan.getText() + "1");
                break;
            case "2":
                screan.setText(screan.getText() + "2");
                break;
            case "3":
                screan.setText(screan.getText() + "3");
                break;
            case "4":
                screan.setText(screan.getText() + "4");
                break;
            case "5":
                screan.setText(screan.getText() + "5");
                break;
            case "6":
                screan.setText(screan.getText() + "6");
                break;
            case "7":
                screan.setText(screan.getText() + "7");
                break;
            case "8":
                screan.setText(screan.getText() + "8");
                break;
            case "9":
                screan.setText(screan.getText() + "9");
                break;

        }


    }//GEN-LAST:event_numberAcion

    private void operatorsAcion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorsAcion
        // TODO add your handling code here:
        if (screan.getText().length() > 0) {
            switch (evt.getActionCommand()) {
                case "+":
                    num1 = Double.valueOf(screan.getText());
                    op = '+';
                    show.setText(num1 + " + ");
                    screan.setText("");
                    break;
                case "-":
                    num1 = Double.valueOf(screan.getText());
                    op = '-';
                    show.setText(num1 + " - ");
                    break;
                case "×":
                    num1 = Double.valueOf(screan.getText());
                    op = '*';
                    show.setText(num1 + " × ");
                    break;
                case "÷":
                    num1 = Double.valueOf(screan.getText());
                    op = '/';
                    show.setText(num1 + " ÷ ");
                    break;

            }
            screan.setText("");

        }
    }//GEN-LAST:event_operatorsAcion

    private void cl_equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_equalActionPerformed
        // TODO add your handling code here:
        if (screan.getText().length() > 0) {
            num2 = Double.valueOf(screan.getText());
        } else {
            num2 = num1;
        }
        double result = 0;
        if (op != '\u0000') {
            switch (op) {
                case '+':
                    result = num1 + num2;
                    break;
                case '-':
                    result = num1 - num2;
                    break;
                case '*':
                    result = num1 * num2;
                    break;
                case '/':
                    result = num1 / num2;
                    break;

            }
            op = '\u0000';

            screan.setText(String.valueOf(result));
            show.setText(show.getText() + num2 + " = ");
    }//GEN-LAST:event_cl_equalActionPerformed
      else {
            screan.setText(String.valueOf(num2));

        }

    }
    private void cl_bointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_bointActionPerformed
        // TODO add your handling code here:
        if (!screan.getText().contains(".")) {
            screan.setText(screan.getText() + ".");
        }

    }//GEN-LAST:event_cl_bointActionPerformed

    private void cl_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_backActionPerformed
        // TODO add your handling code here:
        if (screan.getText().length() > 0) {
            String number = screan.getText().substring(0, screan.getText().length() - 1);
            screan.setText(number);
        }


    }//GEN-LAST:event_cl_backActionPerformed

    private void cl_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cl_clearActionPerformed

        // TODO add your handling code here:
        screan.setText("");
        show.setText("");
    }//GEN-LAST:event_cl_clearActionPerformed

    private void changActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changActionPerformed
        // TODO add your handling code here:
        screan.setText((-1 * Double.valueOf(screan.getText())) + "");
    }//GEN-LAST:event_changActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new calc().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chang;
    private javax.swing.JButton cl_0;
    private javax.swing.JButton cl_1;
    private javax.swing.JButton cl_2;
    private javax.swing.JButton cl_3;
    private javax.swing.JButton cl_4;
    private javax.swing.JButton cl_5;
    private javax.swing.JButton cl_6;
    private javax.swing.JButton cl_7;
    private javax.swing.JButton cl_8;
    private javax.swing.JButton cl_9;
    private javax.swing.JButton cl_add;
    private javax.swing.JButton cl_back;
    private javax.swing.JButton cl_boint;
    private javax.swing.JButton cl_clear;
    private javax.swing.JButton cl_divi;
    private javax.swing.JButton cl_equal;
    private javax.swing.JButton cl_multi;
    private javax.swing.JButton cl_sub;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField screan;
    private javax.swing.JLabel show;
    // End of variables declaration//GEN-END:variables
}
